RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 512
CHUNK_OVERLAP: 128
DATA_PATH: 'data/'
LOG_FILE: 'log_loaded.txt'
MODEL_PATH: 'models/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MAX_NEW_TOKENS: 256
TEMPERATURE: 0.01
# Experimental:
PARENT_CHUNK_SIZE: 1024
PARENT_CHUNK_OVERLAP: 256
CHILD_CHUNK_SIZE: 256
CHILD_CHUNK_OVERLAP: 64
RETRIEVER_PATH: 'retriever.pkl'